---
- name: "Launch requested Job {{ job_template_name }}"
  tower_job_launch:
    job_template:     "{{ job_template_name }}"
    inventory:        "empty-inventory-{{ job_vars['__meta__']['tower']['run_group'] | default('default') }}"
  register:       r_tower_job_launch

- name: Callback with job started event
  include_role:
    name: job_callback
  vars:
    job_callback_stage: main
    job_callback_event: started
    job_callback_message: >-
      {{ job_vars['__meta__']['tower']['action'] }}-{{ job_vars['__meta__']['deployer']['type'] }}-{{ job_vars['__meta__']['deployer']['scm_ref'] }}
    job_callback_data: "{{ r_tower_job_launch }}"

- when: tower_job_timeout|int > 0
  include_tasks: wait-for-job.yml
  vars:
    _tower_job_id: "{{ r_tower_job_launch.id }}"
...
