---
- name:           Prepare any necessary Tower components exist then launch job
  hosts:          localhost
  connection:     local
  gather_facts:   false
  become:         false
  vars:
    job_project_name: >-
      {{
          job_vars['__meta__']['deployer']['type'] ~ '-'
        ~ job_vars['__meta__']['deployer']['scm_ref']
      }}
    job_template_name: >-
      {{
          job_vars['__meta__']['tower']['action'] ~ '-'
        ~ job_vars['__meta__']['deployer']['type'] ~ '-'
        ~ job_vars['__meta__']['deployer']['scm_ref'] ~ '-'
        ~ job_vars['guid']
      }}
    job_forks:                 "{{ job_vars['__meta__']['tower']['forks'] | default(10) }}"
    job_playbook:              "{{  job_vars['__meta__']['deployer']['entry_point'] }}"
    job_template_virtualenv:   "{{  job_vars['__meta__']['deployer']['virtualenv'] | default('') }}"
    _job_template_virtualenv:  "{{ '/opt/rh/virtualenvs/' ~ job_virtualenv if job_virtualenv else '' }}"

    ansible_tower_host:       "{{ lookup('env', 'TOWER_HOST') }}"
    ansible_tower_base_url:   "https://{{ ansible_tower_host }}"
    ansible_tower_username:   "{{ lookup('env', 'TOWER_USERNAME') }}"
    ansible_tower_password:   "{{ lookup('env', 'TOWER_PASSWORD') }}"
    ansible_tower_verify_ssl: "{{ lookup('env', 'TOWER_VERIFY_SSL') | bool }}"

  roles:

    - babylon-security-checks         # IMPORTANT - keep as first role
    - babylon-api-checks              # Validation and additional logging
    - create-job-manifest             # Create a record of job prior to running
    # - babylon-setup-for-new-job       # Select execution instance groups etc
    # - git-tag-lookup                  # Optionally select optimal stage git tag
    - confirm-tower-organization      # Ensure correct organization exists
    - confirm-tower-project           # Confirm correct repo AND tag/reference
    - confirm-tower-job-template      # Create 1 time job template
    - launch-tower-job                # Launch job with callbacks
    - post-job-housekeeping           # Cleanup 1 time objects plus misc cleanup

...
