:toc2:

= Dark Tower API Interface

This document describes the optional and mandatory variables expected by Dark Tower's `job-runner` job template.

NOTE: This document assumes basic familiarity with Ansible Tower and concepts such as Job Templates, Projects etc. 

== Overview

Dark Tower's `job-runner` expects to be called with a JSON payload consisting of at least one, and optionally two, dictionaries:

* `job_vars`
* `secrets`

The entire variable payload can be passed in the `job_vars` dictionary but by using a second dictionary `secrets` a more secure separation of variable can be observed and allow for simpler sharing of the non confidential, and often organization specific, credentials etc.

.Sample "all-in-one" vars file
[source,yaml]
----
job_vars:                                                 <1>
  __meta__:                                               <2>
    deployer:                                             <3>
      scm_type:                 git
      scm_url:                  https://github.com/redhat-cop/agnosticd.git
      scm_ref:                  three-tier-app-prod-1.14
      scm_tag_prefix:           three-tier-app-prod  # Dynamic lookup of latest tag
      type:                     agnosticd # default agnosticd
      entry_point:              ansible/main.yml

    callback:                                             <4>
      url:                      ``
      token:                    `` 

    tower:                                                <5>
      organization:             gpte
      run_group:                emea  # e.g.region hint, stage hint (dev|prod)
      action:                   provision 
                                                          <6>
  guid:                         baby-three-01
  env_type:                     three-tier-app
  email:                        babylon@example.com
  subdomain_base_suffix:        .example.opentlc.com
  own_repo_path:                http://YOUR-REPO-PATH
  cloud_provider:               ec2
  aws_region:                   us-east-1
  aws_hosted_zone_id:           Z3IHLWJZOU9SRT
  key_name:                     ocpkey
  aws_access_key_id:            YOUR-KEY-HERE            
  aws_secret_access_key:        YOUR-SECRET-KEY-HERE
...

----

== High Level Overview of the `job_vars`

. `job_vars` top level dictionary
. `\___meta___` metadata not required to be passed to `agnosticd`
. `deployer` metadata used by Dark Tower to create necessary Tower constructs
. `callback` optional callback data to allow Dark Tower to call back to Anarchy for example
. `tower` metadata specific to Tower internal structures and scheduling


.deployer variables
[cols="4%,4%,5%,5%,38%,38%,6%"]
|=============================================
| Parent | | | Name | Purpose | Example | Optional 


| `job_vars`
| `__meta__`
| `deployer`
|
|
| 
| No 

|
|
| 
| `scm_type`                 
| Type of SCM system
| `git`
| No

|
|
| 
| `scm_url`
| URL of SCM
| https://github.com/redhat-cop/agnosticd.git
| Yes

|
|
| 
| `scm_ref`
| git tag *or* branch to check out
| `three-tier-app-prod-1.14`
| No

|
|
| 
| `scm_tag_prefix`
| git tag prefix to perform lookup of latest version and check out
| `three-tier-app-prod`
| No

|
|
| 
| `type`
| Name of deployer
| `agnosticd`
| Yes

|
|
| 
| `entry_point`
| Path of playbook to start esecution
| `ansible/main.yml`
| Yes

|=============================================


==== Callbacks

Dark Tower supports callbacks when provided with a 

.callback variables
[cols="4%,4%,5%,5%,38%,38%,6%"]
|=============================================
| Parent | | | Name | Purpose | Example | Optional 


| `job_vars`
| `__meta__`
| `callback`
|
|
|
| Yes




|
|
|
| `url`
| Callback URL for Dark Tower to communicate Job Status
| http://reciever.openshift.example.com/callback
| Optional

|
|
|
| `token`
| Callback Token for Dark Tower to authenticate to callback API
| `sY45jk7632ooi43oiu`
| Optional

|=============================================
